fetch("http://localhost:8000/SGIFPMatch", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    Template1:
      "Rk1SACAyMAAAAADwAAABAgFQAMUAxQEAAABjI0B8ABF7AIC9ABNzAECcABf1AIAtAC6CAEDoADNsAEC0AFdxAIA/AFoHAEB8AG14AEBaAG6AAIBAAIYEAICiAIj4AIDFAIpyAIDsAI1oAIDfAJfrAEAaAK+UAIDYALxrAIDAAL5yAIB+AMN7AIBfANYGAIAuANuUAECRAOB7AIBPAOKOAEBNAP+WAIApAQEeAIDDAQV1AIBbAQcRAICFAQmHAEBvARsTAIDUARvdAICfASB4AIAbASWxAICQASqQAIBRAS64AICNATnCAECWATzWAAAA",
    Template2:
      "Rk1SACAyMAAAAADwAAABAgFQAMUAxQEAAABjI0B8ABF7AIC9ABNzAECcABf1AIAtAC6CAEDoADNsAEC0AFdxAIA/AFoHAEB8AG14AEBaAG6AAIBAAIYEAICiAIj4AIDFAIpyAIDsAI1oAIDfAJfrAEAaAK+UAIDYALxrAIDAAL5yAIB+AMN7AIBfANYGAIAuANuUAECRAOB7AIBPAOKOAEBNAP+WAIApAQEeAIDDAQV1AIBbAQcRAICFAQmHAEBvARsTAIDUARvdAICfASB4AIAbASWxAICQASqQAIBRAS64AICNATnCAECWATzWAAAA",
    TemplateFormat: "ISO",
  }),
})
  .then((r) => r.text())
  .then((t) => console.log(t))
  .catch((e) => console.error(e));
