import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/config/auth";
import { db } from "@/prisma/db";
import { AccountStatus } from "@prisma/client";

interface ImportAccountRow {
  accountNumber: string;
  memberNumber?: string;
  institutionNumber?: string;
  accountTypeName: string;
  branchName?: string;
  balance?: number;
  openedAt?: string;
}

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = session.user as any;
    if (!["ADMIN", "BRANCHMANAGER"].includes(user.role)) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    const rows: ImportAccountRow[] = await request.json();
    if (!Array.isArray(rows) || rows.length === 0) {
      return NextResponse.json({ error: "No rows provided" }, { status: 400 });
    }

    const result = { total: rows.length, success: 0, failed: 0, errors: [] as any[] };

    const [accountTypes, branches] = await Promise.all([
      db.accountType.findMany(),
      db.branch.findMany(),
    ]);

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      try {
        if (!row.accountNumber) throw new Error("Missing Account Number");
        if (!row.accountTypeName) throw new Error("Missing Account Type");
        if (!row.memberNumber && !row.institutionNumber) throw new Error("Missing Member/Institution Number");

        const accType = accountTypes.find(
          (t) => t.name.toLowerCase() === row.accountTypeName.toLowerCase()
        );
        if (!accType) throw new Error(`Account Type '${row.accountTypeName}' not found`);

        let branchId = branches[0]?.id;
        if (row.branchName) {
          const branch = branches.find((b) => b.name.toLowerCase() === row.branchName!.toLowerCase());
          if (branch) branchId = branch.id;
        }

        let memberId: string | undefined;
        let institutionId: string | undefined;

        if (row.memberNumber) {
          const member = await db.member.findUnique({ where: { memberNumber: row.memberNumber } });
          if (!member) throw new Error(`Member #${row.memberNumber} not found`);
          memberId = member.id;
        } else if (row.institutionNumber) {
          const inst = await db.institution.findUnique({ where: { institutionNumber: row.institutionNumber } });
          if (!inst) throw new Error(`Institution #${row.institutionNumber} not found`);
          institutionId = inst.id;
        }

        const existing = await db.account.findUnique({ where: { accountNumber: row.accountNumber } });
        if (existing) throw new Error(`Account Number '${row.accountNumber}' already exists`);

        // Share accounts must be funded through the Shares Purchase flow, which
        // records the ShareAccount/ShareTransaction and the 304000 Share Capital
        // GL entry. Bulk import only touches the generic Account.balance and
        // would silently miss that bookkeeping, so reject nonzero opening balances.
        if (accType.isShareAccount && (Number(row.balance) || 0) > 0) {
          throw new Error(
            "Share accounts cannot be bulk-imported with a nonzero opening balance — use the Shares Purchase flow instead",
          );
        }

        await db.account.create({
          data: {
            accountNumber: row.accountNumber,
            memberId,
            institutionId,
            accountTypeId: accType.id,
            branchId,
            balance: Number(row.balance) || 0,
            status: AccountStatus.ACTIVE,
            openedAt: row.openedAt ? new Date(row.openedAt) : new Date(),
            isAutoGenerated: false,
            customNumberApprovedBy: user.id,
            customNumberApprovedAt: new Date(),
          },
        });

        const balance = Number(row.balance) || 0;
        if (balance > 0) {
          const txRef = `IMP-OPEN-${Date.now()}-${i}`;
          const openedAt = row.openedAt ? new Date(row.openedAt) : new Date();

          const txn = await db.transaction.create({
            data: {
              transactionRef: txRef,
              memberId: memberId || null,
              institutionId: institutionId || null,
              accountId: (await db.account.findUnique({ where: { accountNumber: row.accountNumber } }))!.id,
              type: "DEPOSIT" as any,
              amount: balance,
              status: "COMPLETED" as any,
              branchId,
              description: `Opening balance from import`,
              processedByUserId: user.id,
              channel: "CASH",
              transactionDate: openedAt,
            },
          });

          await db.deposit.create({
            data: {
              transactionId: txn.id,
              memberId: memberId || null,
              institutionId: institutionId || null,
              accountId: txn.accountId,
              amount: balance,
              depositDate: openedAt,
              handlerUserId: user.id,
              channel: "CASH",
            },
          });
        }

        result.success++;
      } catch (error) {
        result.failed++;
        result.errors.push({
          row: i + 1,
          error: error instanceof Error ? error.message : "Unknown error",
          data: row,
        });
      }
    }

    return NextResponse.json({ success: true, data: result });
  } catch (error) {
    console.error("Error importing accounts:", error);
    return NextResponse.json({ error: "Failed to import accounts" }, { status: 500 });
  }
}
