import jsPDF from "jspdf";
import { REPORT_HEADER_DETAILS } from "@/lib/report-header";

type PdfOptions = {
  title: string;
  subtitle?: string;
  branchLabel?: string;
  generatedAt?: string;
};

export function renderSaccoPdfHeader(doc: jsPDF, options: PdfOptions) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(3, 22, 53);
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(REPORT_HEADER_DETAILS.institutionName, 12, 11);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(REPORT_HEADER_DETAILS.registrationNumber, 12, 17);
  doc.text(
    `${REPORT_HEADER_DETAILS.postalAddress.join(", ")} | ${REPORT_HEADER_DETAILS.contacts.join(" / ")} | ${REPORT_HEADER_DETAILS.email}`,
    12,
    22,
  );

  doc.setTextColor(3, 22, 53);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(options.title, pageWidth - 12, 12, { align: "right" });

  if (options.subtitle) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(options.subtitle, pageWidth - 12, 17, { align: "right" });
  }

  if (options.branchLabel) {
    doc.setFontSize(8);
    doc.text(`Branch: ${options.branchLabel}`, pageWidth - 12, 22, {
      align: "right",
    });
  }

  if (options.generatedAt) {
    doc.setFontSize(8);
    doc.text(`Generated: ${options.generatedAt}`, pageWidth - 12, 26, {
      align: "right",
    });
  }
}

export function renderSaccoPdfFooter(doc: jsPDF, note = "System generated by Bukonzo United Teachers SACCO.") {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(203, 213, 225);
  doc.line(12, pageHeight - 10, pageWidth - 12, pageHeight - 10);
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(note, 12, pageHeight - 6);
}
