// lib/audit-constants.ts (NO "use server" directive)

export interface AuditLogData {
  userId: string;
  action: string;
  entityType: string;
  entityId?: string;
  oldValue?: any;
  newValue?: any;
  ipAddress?: string;
  browser?: string;
  os?: string;
  userAgent?: string;
  details?: any;
}

// Common audit log actions
export const AUDIT_ACTIONS = {
  // User Management
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",

  // Member Management
  MEMBER_CREATED: "MEMBER_CREATED",
  MEMBER_UPDATED: "MEMBER_UPDATED",
  MEMBER_APPROVED: "MEMBER_APPROVED",
  MEMBER_REJECTED: "MEMBER_REJECTED",

  // Account Management
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
  ACCOUNT_CLOSED: "ACCOUNT_CLOSED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_REACTIVATED: "ACCOUNT_REACTIVATED",
  ACCOUNT_HOLD_PLACED: "ACCOUNT_HOLD_PLACED",
  ACCOUNT_HOLD_LIFTED: "ACCOUNT_HOLD_LIFTED",

  // Transactions
  DEPOSIT_CREATED: "DEPOSIT_CREATED",
  DEPOSIT_COMPLETED: "DEPOSIT_COMPLETED",
  DEPOSIT_FAILED: "DEPOSIT_FAILED",
  DEPOSIT_UPDATED: "DEPOSIT_UPDATED",

  WITHDRAWAL_VERIFICATION_CREATED: "WITHDRAWAL_VERIFICATION_CREATED",
  WITHDRAWAL_VERIFICATION_SENT: "WITHDRAWAL_VERIFICATION_SENT",
  WITHDRAWAL_COMPLETED: "WITHDRAWAL_COMPLETED",
  WITHDRAWAL_FAILED: "WITHDRAWAL_FAILED",
  WITHDRAWAL_UPDATED: "WITHDRAWAL_UPDATED",

  TRANSACTION_CREATED: "TRANSACTION_CREATED",
  TRANSACTION_UPDATED: "TRANSACTION_UPDATED",
  TRANSACTION_REVERSED: "TRANSACTION_REVERSED",

  // Loans
  LOAN_APPLICATION_CREATED: "LOAN_APPLICATION_CREATED",
  LOAN_APPLICATION_APPROVED: "LOAN_APPLICATION_APPROVED",
  LOAN_APPLICATION_REJECTED: "LOAN_APPLICATION_REJECTED",
  LOAN_DISBURSED: "LOAN_DISBURSED",
  LOAN_REPAYMENT_CREATED: "LOAN_REPAYMENT_CREATED",

  // System
  SYSTEM_BACKUP: "SYSTEM_BACKUP",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  SYSTEM_CONFIG_UPDATED: "SYSTEM_CONFIG_UPDATED",

  // Security
  SECURITY_LOGIN_FAILED: "SECURITY_LOGIN_FAILED",
  SECURITY_PASSWORD_RESET: "SECURITY_PASSWORD_RESET",
  SECURITY_ACCOUNT_LOCKED: "SECURITY_ACCOUNT_LOCKED",
} as const;
