"use server";

import { db } from "@/prisma/db";
import { getAuthUser } from "@/config/useAuth";
import { AccountStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";

export interface ImportAccountRow {
  accountNumber: string;
  memberNumber?: string;
  institutionNumber?: string;
  accountTypeName: string;
  branchName?: string;
  balance: number;
  openedAt?: string | Date;
}

export interface ImportResult {
  total: number;
  success: number;
  failed: number;
  errors: Array<{ row: number; error: string; data: any }>;
}

export async function importAccountsBatch(rows: ImportAccountRow[]) {
  const result: ImportResult = {
    total: rows.length,
    success: 0,
    failed: 0,
    errors: [],
  };

  const user = await getAuthUser();
  if (!user) {
    return { error: "Unauthorized" };
  }

  // Optimize: Pre-fetch maps to avoid N+1 queries if possible, 
  // but for safety/simplicity we'll query per row or cache small tables.
  
  // Cache small tables
  const accountTypes = await db.accountType.findMany();
  const branches = await db.branch.findMany();

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    try {
        // 1. Validate mandatory fields
        if (!row.accountNumber) throw new Error("Missing Account Number");
        if (!row.accountTypeName) throw new Error("Missing Account Type");
        if (!row.memberNumber && !row.institutionNumber) throw new Error("Missing Member/Institution Number");

        // 2. Resolve Relations
        // Account Type
        const accType = accountTypes.find(t => 
            t.name.toLowerCase() === row.accountTypeName.toLowerCase()
        );
        if (!accType) throw new Error(`Account Type '${row.accountTypeName}' not found`);

        // Branch
        let branchId = branches[0]?.id; // Default to first branch if missing
        if (row.branchName) {
            const branch = branches.find(b => b.name.toLowerCase() === row.branchName!.toLowerCase());
            if (branch) branchId = branch.id;
        }

        // Owner (Member or Institution)
        let memberId: string | undefined;
        let institutionId: string | undefined;

        if (row.memberNumber) {
            const member = await db.member.findUnique({ where: { memberNumber: row.memberNumber } });
            if (!member) throw new Error(`Member #${row.memberNumber} not found`);
            memberId = member.id;
        } else if (row.institutionNumber) {
             const inst = await db.institution.findUnique({ where: { institutionNumber: row.institutionNumber } });
             if (!inst) throw new Error(`Institution #${row.institutionNumber} not found`);
             institutionId = inst.id;
        }

        // 3. Check for Existing Account
        const existing = await db.account.findUnique({ where: { accountNumber: row.accountNumber } });
        if (existing) throw new Error(`Account Number '${row.accountNumber}' already exists`);

        // 4. Create Account
        await db.account.create({
            data: {
                accountNumber: row.accountNumber,
                memberId,
                institutionId,
                accountTypeId: accType.id,
                branchId,
                balance: Number(row.balance) || 0,
                status: AccountStatus.ACTIVE,
                openedAt: row.openedAt ? new Date(row.openedAt) : new Date(),
                isAutoGenerated: false,
                customNumberApprovedBy: user.id,
                customNumberApprovedAt: new Date(),
            }
        });

        result.success++;

    } catch (error) {
       result.failed++;
       result.errors.push({
           row: i + 1, // 1-indexed for user
           error: error instanceof Error ? error.message : "Unknown error",
           data: row
       });
    }
  }

  revalidatePath("/dashboard/accounts");
  return { success: true, data: result };
}
